### ISSUE TITLE
Repo name standardization vs. non-buffer naming

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/core-authentication-service#11]
The repo has a non-Buffer scoped name `authentication-service` currently. During our documentation/standardization engineering team conversation at retreat someone did mention standardizing repo names like we have for `buffer-js-*` and `buffer-ios-*` etc. I'm wondering if we should rename this `buffer-authentication-service` for consistency?

**Comment by hharnisc** [comment]
Happy to change this to keep it consistent! I was thinking this one was a "shared/core" service (like the session-service) that didn't quite fit within the `buffer` namespace naming convention. What would say to either having no prefix to core services or prefix with `core-*`?

**Comment by djfarrelly** [comment]
Good idea @hharnisc, I've added comments there!

**Comment by hharnisc** [comment]
@djfarrelly I've got a PR open that makes these changes: https://github.com/bufferapp/buffer-dev/pull/143

**Comment by hharnisc** [comment]
changes have already been made in this repo as well :smile:
