### ISSUE TITLE
Requiring/exporting models vs. passing as function args / declaring async

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/core-authentication-service#16]
@hharnisc I'm curious to learn more about your approach of dependency injection using closures for models in the rpc functions. Similar is instantiating the model in a closure using the mongoose connection which I don't believe is necessary (unless you found something I don't know 😃). My guess is that you did this as an approach to injecting dependencies during testing. I would love to hear more of your thoughts!

As an alternative, leveraging node's dependency system/requires:

```js
const authenticationAccountSchema = Schema({
module.exports = mongoose.model('Account', authenticationAccountSchema)
// the above shouldn't require an active mongoose connection I believe
```
```js
const AccountModel = require('./models/Account.js')
module.exports = async function createUser({ email, password }) {
  const u = new AccountModel({ email })
  u.setPassword(password)
  //...
}
```

Mongoose doesn't require the 

Some of my thoughts around patterns like this could be summed up in:

**Unnecessary closures**
I guess also some of this is my desire to stay away from closures unless they're truly needed as they could negatively affect performance or memory usage. I also feel that unnecessary closures can hurt readability...

**Readability**
In requiring a module directly vs. passing it via closure, I find it can be easier to follow from a readability perspective (redux middleware closures really confuse me!). Also, when reading you know exactly where the model file is that you can reference. It might also feel more logical from my thinking that an module called `createUser` exports a function to create a user, not a function to create a function to create a user. This kind of also feels in line with the movement in Node/JS toward `async`/`await` to write more synchronous looking code rather than have too many callbacks/nesting.

**Cleaner call stacks naming the function**
We can do this with the closure model, but using more named functions over anonymous closures will make stack traces clearer.

**Single export as a named function bonus**
As a bonus, using named functions could also help some automatic route naming in the `rpc` library via `Function.name` like `method(createUser)` rather than `method('createUser', createUser)` (see #15 for related ideas where we could also use the file's name itself 😄)

**re: test mocks**
We can also still test using Jest's mocks which might make the mocked model in tests like this more reusable:
https://github.com/bufferapp/authentication-service/blob/b8869b403ce6dcde7ecc3294eca387fc4f784111/tests/createUser.test.js#L12-L16

**Edit** - I just saw the "Mockgoose" npm library if we wanted to test our Mongoose methods without having to spin up a real mongo db: https://www.npmjs.com/package/mockgoose

Let me know what you think here - this is more one of those readability and style patterns we can be deliberate about for the long term maintenance and readability of the code as well as future services!

**Comment by hharnisc** [comment]
Hey @djfarrelly!

Thanks so much for finding the Mockgoose library 🙌 it looks super useful and seems like it would allow us to write some integration tests for the model.

There's some great stuff in here thinking about readability and style patterns. I've also been thinking about this quite a bit as well. I think I need some more time to think through this, would you be up for talking through some of this later once I've had a chance to gather my thoughts?

**Comment by djfarrelly** [comment]
Sure @hharnisc - let's chat next week :) It'll be fun to have an open convo on readability and style patterns

**Comment by djfarrelly** [comment]
Moved to Jira: https://buffer.atlassian.net/browse/ACC-219
