### ISSUE TITLE
Service naming/helm chart config

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/core-authentication-service#33]
Hey @hharnisc, awesome work getting this into production! I had one question that kind of crosses between this service and the the helm chart that this service uses.

I'm assuming that the service name utilizes the name from this service, but I'm not seeing the namespace:

https://github.com/bufferapp/core-authentication-service/blob/569b4edb1ad7ec594f89f1076fb18b5a646a708d/values.yaml#L1-L7

I was thinking since this is already running in the `core` namespace, the `core-` prefix might be redundant. What do you think? 

Also, is there a `namespace` field in our base helm chart that we need to add in the `values.yaml`?

**Comment by hharnisc** [comment]
Core prefix is definitely redundant :smile: I'll change the name. Seeing this all in one place it makes more sense to put the namespace in the `values.yaml`. I'll move that over :smile:
