### ISSUE TITLE
Index at updates_at in MongoDB

### ISSUE THREAD

**Issue by davidgasquez** [bufferapp/core-authentication-service#34]
Hey there @hharnisc! I was looking at the current schema of the Account object and noticed we [don't have an index in the `updated_at` field](https://github.com/bufferapp/core-authentication-service/blob/master/src/models/authenticationAccountModel.js#L56). 

I was curious how hard and expensive (in terms of performance and $) would be to add an index there. We might not use it never but sometimes it makes doing backups really easy (query and upsert).

For the data pipeline I was thinking about using MongoDB 3.6 new feature [`ChangeStream`](https://docs.mongodb.com/manual/changeStreams/). Basically, we'll be tracking all the changes in the collection (the internal WAL MongoDB uses for replication) and sending and applying the changes downstream. 

We don't need `updated_at` at all to make this approach work. But, in case a lot of things were going wrong, having it will give us the option to query secondary nodes for a list of documents updated in the last _period of time_. 

No pressure at all adding the index since is not required at all, just wanted to check. Thanks!

**Comment by djfarrelly** [comment]
@davidgasquez, would we be able to do queries like this from the secondary which would make them less expensive? I'm just thinking the overhead of adding another index that we won't use in the application 😄 

I think that this collection will get larger, but since the document is small, querying or dumping this collection from the secondary shouldn't be too bad to pull for backups. What do you think?

**Comment by davidgasquez** [comment]
Heya @djfarrelly! That sounds perfect. We don't need it to be super up to date so we can totally use secondary nodes for this.

I just wanted to suggest this in case adding an extra index didn't affect production workloads. With Change Streams, we won't need to use this approach at all but its always nice to have a backup plan in mind! :wink:
